// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXfYQWMh8mbphRn_vbuu1iGn8vuDSH5xw',
    appId: '1:155857162114:web:8beac23107b015e15d499b',
    messagingSenderId: '155857162114',
    projectId: 'lnt-simple-ewallet',
    authDomain: 'lnt-simple-ewallet.firebaseapp.com',
    storageBucket: 'lnt-simple-ewallet.appspot.com',
    measurementId: 'G-EE7YF7HDRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJmoabPLR4t0X2X8a9_iBgRJOSySZsOQw',
    appId: '1:155857162114:android:22fa22742cb74bf55d499b',
    messagingSenderId: '155857162114',
    projectId: 'lnt-simple-ewallet',
    storageBucket: 'lnt-simple-ewallet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjEjXZUsiiflBDpxhbeBJT3G8AeJwSJqQ',
    appId: '1:155857162114:ios:3cd6ca609d810e4c5d499b',
    messagingSenderId: '155857162114',
    projectId: 'lnt-simple-ewallet',
    storageBucket: 'lnt-simple-ewallet.appspot.com',
    iosBundleId: 'com.example.lntSimpleEwallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjEjXZUsiiflBDpxhbeBJT3G8AeJwSJqQ',
    appId: '1:155857162114:ios:3cd6ca609d810e4c5d499b',
    messagingSenderId: '155857162114',
    projectId: 'lnt-simple-ewallet',
    storageBucket: 'lnt-simple-ewallet.appspot.com',
    iosBundleId: 'com.example.lntSimpleEwallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXfYQWMh8mbphRn_vbuu1iGn8vuDSH5xw',
    appId: '1:155857162114:web:303383fb0eb5d60b5d499b',
    messagingSenderId: '155857162114',
    projectId: 'lnt-simple-ewallet',
    authDomain: 'lnt-simple-ewallet.firebaseapp.com',
    storageBucket: 'lnt-simple-ewallet.appspot.com',
    measurementId: 'G-T6HKG2E47W',
  );
}
